version: "2.3"

services:
  redis:
    restart: "always"
    mem_limit: 1G
    container_name: redis_backend

    image: redis:6.2-alpine
    
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'

  rabbitmq:
    restart: "always"
    mem_limit: 2G
    container_name: rabbitmq_broker

    image: "rabbitmq:3-management"

    ports:
      - 5672:5672  # Порт для AMQP
      - 15672:15672  # Порт для RabbitMQ Management

    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia
      - ./rabbit_conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_LOGIN}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWD}
  
  worker:
    restart: "always"
    mem_limit: 8G
    container_name: worker

    build: 
      context: ./neural_worker
      dockerfile: Dockerfile
    # command: bash -c "celery -A celery_services worker -l info -E -c 3 --loglevel=info"
    command: bash -c "celery -A celery_services worker -l info -E -P solo --loglevel=info"

    environment:
      - CELERY_BROKER_URL=${RABBITMQ_IP}
      - CELERY_RESULT_BACKEND=${REDIS_IP}
      - OPENAI_KEY=${OPENAI_KEY}
      - BASE_OPENAI_URL=${BASE_OPENAI_URL}
      
    depends_on:
      - redis
      - rabbitmq
      
  celery-flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=${RABBITMQ_IP}']

    environment:
      - FLOWER_PORT=5555

    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  api:
    restart: "always"
    mem_limit: 4G
    container_name: api

    build: 
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 5050"

    environment:
      - CELERY_BROKER_URL=${RABBITMQ_IP}
      - CELERY_RESULT_BACKEND=${REDIS_IP}

    ports:
      - 5050:5050

    depends_on:
      - celery-flower
      - worker
      - rabbitmq

