"""Init

Revision ID: 113341de12cd
Revises: 
Create Date: 2025-01-24 22:53:32.647795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113341de12cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('s3_md_id', sa.String(length=50), nullable=True),
    sa.Column('s3_raw_id', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('common_share_role_type', sa.Enum('private', 'viewer', 'edit', name='shareroleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('sub_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_level_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('document_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('last_access_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('owner', 'viewer', 'editor', name='roleenum'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_users')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('documents')
    # ### end Alembic commands ###
